---
title: P162MRV144 gene-expression microarrays preprocessing
author: Slim Fourati
date: February 6, 2017
output: github_documents
---

Loading require packages
```{r, loading-packages}
suppressPackageStartupMessages(library(package = "knitr"))
suppressPackageStartupMessages(library(package = "Biobase"))
suppressPackageStartupMessages(library(package = "impute"))
suppressPackageStartupMessages(library(package = "limma"))
suppressPackageStartupMessages(library(package = "tidyverse"))
```

set default options/variables
```{r, global-variables}
workDir <- dirname(getwd())
opts_chunk$set(tidy = FALSE, fig.path = "../figure/")
options(stringsAsFactors = FALSE, width = 80, readr.num_columns = 0)
```

read non-normalized matrix
```{r, read-raw-matrix, warning=FALSE}
rawFile <- file.path(workDir,
  "input/GA_illumina_expression.p162.matrix_non_norm.csv")
rawMat <- read_csv(file = rawFile, progress = FALSE)
```

read arrays annotation
```{r, reading-arrays-annotation}
arraysAnnotFile <- file.path(workDir,
                             "input/GA_illumina_expression.p162.metadata.csv")
arraysAnnotation <- read_csv(file = arraysAnnotFile, progress = FALSE)
# remove unused phenotypic information
arraysAnnotation <- select(arraysAnnotation,
                           -title,
                           -`source name`,
                           -organism,
                           -molecule,
                           -label,
                           -description,
                           -platform)
# remove prefix 'characteristics` of column names
names(arraysAnnotation) <- gsub(pattern = "^[^:]+: (.+)$",
                                replacement = "\\1",
                                names(arraysAnnotation))
```

read features annotation
```{r, reading-features-annotation}
featuresAnnotFile <- file.path(workDir,
                               "input/Illumina_HumanHT12_V4.rheMac3.chip")
featuresAnnotation <- read_tsv(file = featuresAnnotFile, progress = FALSE) %>%
  as.data.frame()
rownames(featuresAnnotation) <- featuresAnnotation$IlmnID
```

create non-normalized ExpressionSet
```{r, create-raw-eset}
# format raw matrix
rNames <- rawMat$"ID_REF"
rawMat <- rawMat[, -grep(pattern = "ID_REF|Detection Pval",
                         colnames(rawMat))]
rawMat <- as.matrix(rawMat)
rownames(rawMat) <- rNames
# format phenodata
arraysAnnotation <- as.data.frame(arraysAnnotation)
rownames(arraysAnnotation) <- arraysAnnotation$"Sample name"
arraysAnnotation <- arraysAnnotation[colnames(rawMat), ]
# format feature annotation
featuresAnnotation <- as.data.frame(featuresAnnotation)
featuresAnnotation <- featuresAnnotation[rownames(rawMat), ]
# create ExpressionSet
esetRaw <- ExpressionSet(assayData   = rawMat,
                         phenoData   = AnnotatedDataFrame(arraysAnnotation),
                         featureData = AnnotatedDataFrame(featuresAnnotation))
# save raw ExpressionSet
save(esetRaw, file = file.path(workDir, "output/p162.esetRaw.RData"))
```

normalizing raw expression
```{r, normalization}
eset <- esetRaw
# order esetRaw by idat file name and features by ProbeID
eset <- eset[order(as.numeric(fData(eset)$ProbeID)),
             order(eset$"idat file")]
# impute missing intensities (intensities = 0)
rawMat <- exprs(eset)
rawMat[rawMat == 0] <- NA
suppressWarnings(capture.output(rawMat <- impute.knn(data = rawMat)$data,
                                file = "/dev/null"))
exprs(eset) <- rawMat
# quantile normalized and log2 transform expression
normMat <- normalizeBetweenArrays(exprs(eset), method = "quantile")
# variance stabilization
normMat <- log2(normMat)
exprs(eset) <- normMat
# average technical replicate
flag <- pData(eset) %>%
  mutate(ID = paste0(donor, ".", `vaccination time`)) %>%
  filter(duplicated(ID)) %>%
  .$ID
replicated <- pData(eset) %>%
  mutate(ID = paste0(donor, ".", `vaccination time`)) %>%
  filter(ID %in% flag)
for (dupID in unique(replicated$ID)) {
  dupSample <- replicated %>%
    filter(ID %in% dupID) %>%
    .$"Sample name"
  exprs(eset)[, sampleNames(eset) %in% dupSample[1]] <-
    apply(exprs(eset[, sampleNames(eset) %in% dupSample]),
          MARGIN = 1,
          FUN    = mean)
  # remove others from the eset
  eset <- eset[, !(sampleNames(eset) %in% dupSample[2:length(dupSample)])]
}
# save normalized ExpressionSet
save(eset, file = file.path(workDir, "output/p162.eset.RData"))
```

create a postvax-prevax ExpressionSet
```{r, substracted-eset}
# identify complete pair of postvax-prevax stimulated samples
flag <- pData(eset) %>%
  select(`Sample name`,
         donor,
        `vaccination time`) %>%
  spread(`vaccination time`, `Sample name`) %>%
  gather(`Vaccination time`, postvax, -donor, -`pre-vaccination`)
esetBaselined <- eset[, flag$postvax]
exprs(esetBaselined) <- exprs(esetBaselined) -
    exprs(eset[, flag$"pre-vaccination"])
# save postvax-prevax expression
save(esetBaselined, file = file.path(workDir, "output/p162.esetBaselined.RData"))
```

regression analysis: vaccine-conferred protection
```{r, deg-protection}
fits <- list()
# linear regressions on pre- and post-vax expression
# seperated by prime/immunization/timepoint
groupOfInterest <- pData(eset) %>%
  mutate(adjuvant        = gsub(pattern     = ".+/([^/]+)$",
                                replacement = "\\1",
                                `vaccination group`),
         immunization    = gsub(pattern     = "-| immunization|vaccination",
                                replacement = "",
                                `vaccination time`),
         groupOfInterest = interaction(adjuvant,
                                       immunization,
                                       drop = TRUE)) %>%
  .$groupOfInterest
for (goi in levels(groupOfInterest)) {
  esetTemp <- eset[, groupOfInterest %in% goi]
  # create the variable of interest
  challenge <- pData(esetTemp) %>%
               mutate(challenge =
                      gsub(pattern     = "neg",
                           replacement = 11,
                           `number of SIV challenge to infection`),
                      challenge = as.numeric(challenge)) %>%
               .$challenge
  design <- model.matrix(~challenge)
  rownames(design) <- sampleNames(esetTemp)
  fit <- lmFit(esetTemp, design = design)
  fit2 <- eBayes(fit = fit)
  # save MArrayLM in list
  fits[[paste0(goi, "_challenge")]] <- list(fit = fit, fit2 = fit2)
}

# linear regressions on baselined expression
# seperated by prime/immunization/timepoint
groupOfInterest <- pData(esetBaselined) %>%
  mutate(adjuvant = gsub(pattern     = ".+/([^/]+)$",
                         replacement = "\\1",
                         `vaccination group`),
         immunization = gsub(pattern     = "-| immunization",
                             replacement = "",
                             `vaccination time`),
         groupOfInterest = interaction(adjuvant,
                                       immunization,
                                       drop = TRUE)) %>%
  .$groupOfInterest
for (goi in levels(groupOfInterest)) {
  esetTemp <- esetBaselined[, groupOfInterest %in% goi]
  # create the variable of interest
  challenge <- pData(esetTemp) %>%
               mutate(challenge =
                      gsub(pattern     = "neg",
                           replacement = 11,
                           `number of SIV challenge to infection`),
                      challenge = as.numeric(challenge)) %>%
               .$challenge
  design <- model.matrix(~challenge)
  rownames(design) <- sampleNames(esetTemp)
  fit <- lmFit(esetTemp, design = design)
  fit2 <- eBayes(fit = fit)
  # save MArrayLM in list
  fits[[paste0(goi, ".baselined_challenge")]] <- list(fit = fit, fit2 = fit2)
}

# save MArrayLM list
save(fits, file = file.path(workDir, file.path("output/p162.fits.RData")))
```

print session info
```{r, session-info}
sessionInfo()
```
